name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build Docker image: ubuntu-fat"
      run: docker build . --file ubuntu-fat/Dockerfile --tag ubuntu-fat:$(date +%s)
